---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  vars_files:
    -  vaul-pass.yml
  tasks:
  - name: clone a repo
    git:
      repo: https://newbieht7:{{ password }}github.com/newbie7ht/Projects.git
      dest: /opt/ansible/test-vault

# now the variable file is encrypted so we have to run the command as below
 # ansible-playbook -i hosts Vault-password-as-variable.yml --ask-vault-pass

# this will ask the password now provide the password and the playbook will run

# another way

# ansible-playbook -i hosts Vault-password-as-variable.yml --vault-password-file vaul-pass.yml